# Generated by Django 5.0.6 on 2026-08-13 06:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('github_repo', 'GitHub Repository'), ('upload', 'Uploaded File Set'), ('wiki_export', 'Wiki Export')], max_length=32)),
                ('name', models.CharField(max_length=255)),
                ('credentials_ref', models.CharField(blank=True, max_length=255)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('sync_status', models.CharField(choices=[('pending', 'Pending'), ('syncing', 'Syncing'), ('synced', 'Synced'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='workspaces.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='Artifact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('path', models.CharField(max_length=1024)),
                ('content_hash', models.CharField(db_index=True, max_length=64)),
                ('version', models.CharField(blank=True, max_length=64)),
                ('raw_text', models.TextField(blank=True)),
                ('file_type', models.CharField(blank=True, max_length=32)),
                ('agent_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('completed_heuristic', 'Completed with heuristic fallback'), ('failed', 'Failed')], default='pending', max_length=32)),
                ('agent_status_message', models.TextField(blank=True)),
                ('claim_extraction_method', models.CharField(blank=True, max_length=16)),
                ('last_scanned_at', models.DateTimeField(blank=True, null=True)),
                ('extraction_status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('heuristic', 'Heuristic'), ('failed', 'Failed')], default='pending', max_length=32)),
                ('extraction_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='sources.source')),
            ],
            options={
                'indexes': [models.Index(fields=['source', 'content_hash'], name='sources_art_source__dcaf3c_idx')],
                'unique_together': {('source', 'path')},
            },
        ),
    ]
