# Generated by Django 5.0.6 on 2026-08-13 06:57

import django.db.models.deletion
import pgvector.django
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sources', '0001_initial'),
        ('workspaces', '0001_initial'),
    ]

    operations = [
        pgvector.django.VectorExtension(),
        migrations.CreateModel(
            name='Chunk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('embedding', pgvector.django.VectorField(blank=True, dimensions=3072, null=True)),
                ('token_count', models.PositiveIntegerField(default=0)),
                ('position', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('artifact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='sources.artifact')),
            ],
            options={
                'ordering': ['artifact', 'position'],
            },
        ),
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('statement', models.TextField()),
                ('category', models.CharField(choices=[('endpoint', 'Endpoint'), ('config_value', 'Config Value'), ('process_step', 'Process Step'), ('version_number', 'Version Number')], max_length=32)),
                ('confidence', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('artifact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='sources.artifact')),
                ('chunk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claims', to='knowledge.chunk')),
            ],
        ),
        migrations.CreateModel(
            name='ScanRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trigger', models.CharField(choices=[('webhook', 'Webhook'), ('scheduled', 'Scheduled'), ('manual', 'Manual')], max_length=16)),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('completed_with_fallback', 'Completed with heuristic fallback'), ('failed', 'Failed')], default='running', max_length=32)),
                ('failure_message', models.TextField(blank=True)),
                ('statistics', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_runs', to='workspaces.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='Inconsistency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('major', 'Major'), ('minor', 'Minor')], max_length=16)),
                ('status', models.CharField(choices=[('open', 'Open'), ('acknowledged', 'Acknowledged'), ('fixed', 'Fixed'), ('false_positive', 'False Positive')], default='open', max_length=16)),
                ('agent_reasoning', models.TextField(blank=True)),
                ('suggested_fix', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('claims', models.ManyToManyField(related_name='inconsistencies', to='knowledge.claim')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inconsistencies', to='workspaces.workspace')),
                ('scan_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inconsistencies', to='knowledge.scanrun')),
            ],
        ),
        migrations.AddConstraint(
            model_name='chunk',
            constraint=models.UniqueConstraint(fields=('artifact', 'position'), name='unique_chunk_artifact_position'),
        ),
    ]
