# Generated by Django 5.0.6 on 2026-08-13 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(default='github', max_length=32)),
                ('delivery_id', models.CharField(max_length=128)),
                ('event_type', models.CharField(blank=True, max_length=64)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed', models.BooleanField(default=False)),
            ],
            options={
                'unique_together': {('provider', 'delivery_id')},
            },
        ),
    ]
